site_name: Proyecto Intermodular ASIR

nav:
  - Inicio: index.md
  - Introducción: 01_introduccion.md
  - Arquitectura y Servicios: 02_arquitectura.md
  - Seguridad y Copias: 03_seguridad_copias.md
  - Implantación y Pruebas: 04_implantacion_pruebas.md
